### ISSUE TITLE
in gedit 3.20.1 arch

### ISSUE THREAD

**Issue by Arion-Dsh** [isamert/gedi#2]
it not show the complete popups. here is my traceback. is it usefull?

Traceback (most recent call last):
  File "/home/xxx/.local/share/gedit/plugins/gedi/gedi.py", line 87, in do_populate
    self.get_icon_for_type(completion.type.lower()),
  File "/home/arion/.local/share/gedit/plugins/gedi/gedi.py", line 105, in get_icon_for_type
    return theme.load_icon(Gtk.STOCK_ADD, 16, 0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'gtk-add' not present in theme Adwaita (0)

**Comment by benmoran56** [comment]
I'm not the developer, but I think this is related to a missing icon in your current theme. If you're on an older Gnome 3 version, it could be that that specific icon doesn't exist (yet). If you have any other icon themes installed, you could try switching to one of them using the gnome-tweak-tool. Otherwise, maybe the developer could switch to a different icon that exists in older Gnome3 version's default theme. 

Edit:   Just read the title of your bug report, and saw the "3.20.1" in there. Oops! Don't know how I missed that. Anyhow, try re-installing the adwaita-icon-theme package.

**Comment by isamert** [comment]
You probably don't have the default icon theme. As @benmoran56 said, re-installing adwaita-icon-theme can help. Nevertheless, I'll make a fix for this.

**Comment by Arion-Dsh** [comment]
rocks! it's works. thx
